Makefile, api_test.go, client/client.go, proxy_test.go
Starting to extract the helper methods from `api_test.go` into `client/` which can be used as a Go HTTP client.
I'll extract the toxics and fix the error messages in a follow up PR. Just wanted to commit tonight's work to commit to finishing the job. :-)
@wvanbergen this is primarily meant for you for `kafkabridge`. Please review along with @xthexder 
CI is failing due to subpackage thing... I'll take  a look tomorrow
=> client: initial commit of go client

link.go, proxy_test.go, toxic.go, toxic_test.go
@Sirupsen @graemej 
Fixes the following panic / race condition:
```
2015-04-28_02:00:30.60319 panic: send on closed channel
2015-04-28_02:00:30.60320 
2015-04-28_02:00:30.60320 goroutine 475 [running]:
2015-04-28_02:00:30.60322 main.(*LatencyToxic).Pipe(0xc20800b3a0, 0xc2082ad920)
2015-04-28_02:00:30.60323 	/Users/sirup/src/go/src/github.com/Shopify/toxiproxy/toxic_latency.go:53 +0x2b7
2015-04-28_02:00:30.60323 created by main.(*ToxicLink).Start
2015-04-28_02:00:30.60325 	/Users/sirup/src/go/src/github.com/Shopify/toxiproxy/link.go:60 +0x223
```
This only seems to happen with GOMAXPROCS > 1. Here's the flow that causes a panic:
```
1. Latency toxic is waiting for delay to finish an is interrupted (toxic_latency.go#L52)
2. Before inflight data is sent to output channel, the new toxic is …
```
=> Fix race condition causing write to closed channel panic

io_chan.go, io_chan_test.go, link.go, toxic.go, toxic_latency.go, toxic_noop.go, toxic_slow_close.go, toxic_test.go
@Sirupsen @pushrax 
Changes the latency toxic to better model network latency.
Previously the latency toxic would insert a delay after each "packet", and these would accumulate for large amounts of data.
This PR changes toxiproxy to calculate the delay based on the receive time of the "packet".
=> Change latency toxic to account for buffering

CHANGELOG.md, README.md, api.go, api_test.go, client/client.go
@Sirupsen 
Implements changes proposed in https://github.com/Shopify/toxiproxy/issues/36
Will have to look at what uses this endpoint. I think it may just be turbobar.
The ruby client does not use this endpoint.
=> Remove /toxics endpoint in favour of /proxies

api.go, api_test.go, client/client.go
Fixes https://github.com/Shopify/toxiproxy/issues/51 and gives better errors back form the go api
@Sirupsen
=> Change error handling, and check for blank proxy names

README.md
Anchors are case-sensitive by specification, so "#Clients" does not work.
Some anchors were not relative, and were corrected.
=> *Tiny* changes to anchors in README

CHANGELOG.md, link.go, toxic_test.go
Due to the blocking channels inbetween toxics, the latency toxic was causing TCP reads to block, and thus slowing down the the maximum bandwidth of the toxic.
This change allows some buffering between toxics, which fixes the issue (until the buffer fills up, which will only happen at extremely high throughput + high latency configurations)
@Sirupsen @pushrax for review
=> Fix latency bandwidth

CHANGELOG.md, README.md, toxic_collection.go, toxic_slicer.go, toxic_test.go
When working on relative low-level network applications/clients, it's easy to assume that TCP data will always some in nice grouped "packets" that have all the data you need in them, rather than viewing the connection as a stream. When working locally that may even be its apparent behaviour, but over real-world network connections that's certainly not something that can be relied upon.
This PR adds a "slicer" filter which takes data and slices it up into nice little random chunks before sending them out. The slider also includes a simple delay option, to bypass buffering behaviour that could otherwise nullify the sliced bytes.
=> Add toxic slicer

Makefile, README.md
It would be really useful for me to be able to link to an official windows executable for the [.net client](https://github.com/mdevilliers/toxiproxy).
To aid this I've added a build to the makefile to produce an windows exe for amd64.
To enable cross compilation of windows on linux, darwin follow the instructions at https://github.com/golang/go/wiki/WindowsCrossCompiling. 
then run make.bash enabling windows and amd64
```
cd $GOROOT/src
GOOS=windows GOARCH=amd64 ./make.bash --no-clean
```
Mark
=> Added a windows build to the makefile

CHANGELOG.md, toxic_test.go
@Sirupsen @pushrax 
If the timeout is hit, the tests will hang on `output <- data` inside the toxic, this fixes that.
I also increased the timeout slightly since I ran into it once when my VM was running a little slow.
cc @connor4312
=> Fix slicer test race / deadlock

link_test.go, toxic_collection.go, toxics/toxic.go
@Sirupsen @tomblench
Implements the `toxicity` field from https://github.com/Shopify/toxiproxy/pull/65 globally using the 2.0 toxic architecture.
Usage docs will appear in https://github.com/Shopify/toxiproxy/pull/74
=> Add toxicity field

stream/io_chan.go, stream/io_chan_test.go
In order for `ChanReader` and `ChanWriter` to be used inside toxics, they need be interruptable.
This PR allows them to take the toxic's `interrupt` channel as a parameter, and unblock and reads.
@Sirupsen @eapache
=> Make ChanReader interruptable

Dockerfile, Makefile, README.md, version.go
Instead of using a hacky sed script to write the `VERSION` file into `version.go`, this uses the `-X` parameter of the linker.
I also made the default operation of `make` to be a dev build instead of a full release.
Dev builds will now show up as version `git-<sha>` instead of the previous release. If just `go build` is used, the version will be just `git`
@Sirupsen
=> Clean up Makefile

api.go, api_test.go, client/client.go, toxic_collection.go, toxics/toxic.go
This code is kind of a mess, but it turns out there's no way to marshal a `ToxicWrapper` into a flat object without doing this hacky reflection.
The json package will marshal it as `{"toxic":{"latency": 1000}, "name": "latency")`, which isn't what we want.
Somehow this escaped the tests before, so I've added a bunch of checks to make sure it's covered.
While I was adding checks, I also found out that toxicitiy wasn't set when updating an existing toxic.
@Sirupsen @eapache
=> Fix toxic marhsaling and toxicity updating

toxics/latency.go, toxics/latency_test.go
Multiple latency toxics previously did not stack their delays. Latency toxics now reset their data's `Timestamp` before output.
**Pros:** Easy fix that *just works*
**Cons:** Changing `Timestamp` state that might want to be used by other toxics in the future.
*Decided to create a new test rather than make the original latency test support multiple toxics.*
Sorry to ping you again @xthexder but you seem to know the most about this.
Also @Sirupsen, see https://github.com/Shopify/toxiproxy/pull/83#issuecomment-178224768 and https://github.com/Shopify/toxiproxy/pull/83#issuecomment-178221647
=> latency toxic should reset Timestamp on output

CHANGELOG.md, api.go, api_test.go, client/client.go, toxic_collection.go
> Would it be simpler to return an array of toxics instead of a map with the names as keys?
This changes the api to return a list of toxics rather than a map of name to toxic.
I did not change how toxics are implemented internally. Instead, this is a front end change.
@Sirupsen and @xthexder were unsure about whether this is needed.
```
"toxics": {
"myToxic1": {"name": "myToxic1"...},
"myToxic2": {"name": "myToxic2"...}
}
```
```
"toxics": [
{"name": "myToxic1"...},
{"name": "myToxic2"...}
]
```
=> api: toxics are sent to client as array rather than map

README.md
[toxiproxy-java](https://github.com/trekawek/toxiproxy-java) is a Java client for the Toxiproxy RESTful API.
=> Add toxiproxy-java reference to the README file

api_test.go, toxic_collection.go
Change default toxic name to `<type>_<stream>`.
@Sirupsen
=> make default toxic name type_stream

link.go, stream/io_chan.go, stream/io_chan_test.go, toxics/toxic.go
Fixes https://github.com/Shopify/toxiproxy/issues/88
The order toxics were interrupted caused the api to hang, since the first toxic would try to flush data to the second (which in the case of a timeout toxic will never happen).
This PR changes the operation so that the timeout is interrupted first, and then make sure the previous toxic is able to complete by manually flushing data.
@Sirupsen @sunblaze @pushrax
=> Fix removing timeout toxic hang

CHANGELOG.md, README.md, api_test.go, client/README.md, client/client.go, toxic_collection.go, toxics/toxic.go, toxics/toxic_test.go
This patch embeds toxic specific attributes into their own nested `attributes` field, allowing for the following api changes:
``` go
type Attributes map[string]interface{}
type Toxic struct {
Name       string     `json:"name"`
Type       string     `json:"type"`
Stream     string     `json:"stream"`
Toxicity   float32    `json:"toxicity"`
Attributes Attributes `json:"attributes"`
}
AddToxic(name, typeName, stream string, toxicity float32, attrs Attributes)
UpdateToxic(name string, toxicity float32, attrs Attributes)
```
We can't marshal the attributes of a toxic until we know what kind of toxic struct to marshal into. This has previously forced us to [parse the json twice](https://github.com/Shopify/toxiproxy/blob/d21a2744e6275eb5312b11ab978656fd7cad50bc/toxic_collection.go#L95).
I can't …
=> Embed toxic attribute

.gitignore, CHANGELOG.md, Makefile, api_test.go, cli/cli.go, client/client.go, link.go, toxic_collection.go
Here's `toxiproxy-client` v2.0!
Not worrying about clear commit history when doing rapid ux changes.
I'll start with a quick list of changes, followed by relevant screen shots.
1. Updated version number to 2.0
2. Removed graphic pipe in `inspect` because I found it confusing
3. Made `inspect` a lot clearer
4. Made `list` a lot clearer. Also table has `Toxic` and `Enabled` column
5. Added cyan hints (might be kinda silly?)
6. Added usage and examples to toplevel command and `toxic` command
7. Updated the `makefile` (@Sirupsen: would you glance at this, I'm a little rusty with make)
Part of the toplevel help screen.
Part of the `./cli toxic` screen.
Looks like we havn't created any toxics yet...
There's one!
Let's try to inspect it!
No toxics? Let's add one!
Darn! It defaulted to …
=> Cli 2.0 dev

README.md
Add missing http route endpoint for creating toxics in the readme.
=> Add missing http route endpoint for creating toxics in the readme.

Godeps/Godeps.json, cli/cli.go, toxics/latency_test.go
Tried to build recently (from a new Go installation) and while the build succeeded, trying to list the existing proxies from the cli command yielded a deprecation warning:
```
➜  toxiproxy git:(master) ./toxiproxy-cli list
Listen		Upstream	Name	Enabled	Toxics
======================================================================
no proxies
Hint: create a proxy with `toxiproxy-cli create`
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```
Looks like the `codegangsta/cli` package has been moved to `urface/cli`, according to that package's …
=> Updates to use replacement cli package.

CHANGELOG.md, CREATING_TOXICS.md, Makefile, README.md, link.go, link_test.go, toxic_collection.go, toxics/limit_data.go, toxics/limit_data_test.go, toxics/toxic.go
Adds https://github.com/Shopify/toxiproxy/pull/125 with some fixes
I made some simplifications to `toxic_collection.go` that don't change anything other than make the code look nicer (no more duplicated `c.chain` and `c.toxics`)
Stateful toxics are added to allow for per-connection toxic state to be stored.
This fixes the issue of `bytesTransmitted` in the limit_data toxic being shared between connections.
@Sirupsen @pushrax 
cc @matez
=> Add limit data toxic

CHANGELOG.md, cli/cli.go
Adds `--host / -h` to specify the toxiproxy host to connect to.
For https://github.com/Shopify/toxiproxy/issues/128
@Sirupsen 
cc @dylanahsmith
=> Change cli to allow remote toxiproxy hosts

Dockerfile
Upgrade Go version to 1.7, and also build the CLI.
Adapt GOPATH and PATH to launch the CLI directly from a `docker exec`
=> Dockerfile: upgrade to go 1.7 and build the CLI

CHANGELOG.md, README.md, api.go, api_test.go, client/client.go, proxy.go, proxy_collection.go, proxy_test.go, toxics/toxic_test.go
Here's a WIP first draft for a Populate endpoint solving #102.
(The code can be made prettier and some names / types need to be changed to stick with the old API.)
The endpoint takes a slice of proxies, loop through them doing the standard CreateProxy code. If one of the proxies fails to be created, it deletes the already created proxies before returning the error to the user.
**Should we be making this transactional? There are current errors that can occur that won't trigger the transaction to fail.**
Hoping I could get a review of the general approach.
@Sirupsen @xthexder 
cc: @BlakeMesdag
=> Add a populate endpoint

CHANGELOG.md, cli/cli.go
The cli has proven itself to be very useful for quickly testing things, but until now it hasn't been very useful as part of scripts and automation.
This PR adds some checks to see if a real TTY is being used, and changes the output format if the cli is used as part of a pipe:
```
∙ ./toxiproxy-cli list
Name   			Listen 		Upstream       		Enabled		Toxics
======================================================================================
4      			[::]:8083      	google.com:80  		enabled		None
google 			[::]:8080      	google.com:80  		enabled		3
google2			[::]:8081      	google.com:80  		enabled		None
google3longggggg       	[::]:8082      	google.com:80  		enabled		None
Hint: inspect toxics with `toxiproxy-cli inspect <proxyName>`
∙ ./toxiproxy-cli list | cat
4      	[::]:8083 …
```
=> Scriptable CLI

cli/cli.go
Examples for toxic CLI command are out of date: `-f` option is now `-a`.
=> Update toxic CLI examples

Dockerfile, Makefile, dev.yml
This builds a leaner container for toxiproxy. 
Originally we were building the toxiproxy container and including the entire golang runtime in the container.
```
shiv@Shiv-Mac toxiproxy (master) $ docker build --tag="shopify/toxiproxy:2.0.0" .
Sending build context to Docker daemon 17.34 MB
Step 1/6 : FROM golang:1.7
---> ef15416724f6
Step 2/6 : COPY . /go/src/github.com/Shopify/toxiproxy
---> 52f7c3acd605
Removing intermediate container 1cd1617aa433
Step 3/6 : RUN go build -ldflags="-X github.com/Shopify/toxiproxy.Version=$(cat /go/src/github.com/Shopify/toxiproxy/VERSION)" -o /go/bin/toxiproxy github.com/Shopify/toxiproxy/cmd &&     go build -o /go/bin/toxiproxy-cli github.com/Shopify/toxiproxy/cli
---> Running in 8b028157f1f8
---> b60805b8fd09
Removing intermediate container …
```
=> build a leaner toxiproxy container

CHANGELOG.md, README.md, api.go, cmd/toxiproxy.go, proxy_collection.go
I'd like to get a 2.1.0 released soon, since there's a lot of unreleased features piling up.
I put together the functionality described in https://github.com/Shopify/toxiproxy/pull/153 in this PR so we can get it included in 2.1.0
Example:
```
[
{
"name": "redis",
"upstream": "localhost:6379",
"listen": "localhost:6380"
}
]
```
```
$ ./toxiproxy-server -config test.json
INFO[0000] Started proxy                                 name=redis proxy=127.0.0.1:6380 upstream=localhost:6379
INFO[0000] Populated proxies from file                   config=test.json proxies=1
INFO[0000] API HTTP server starting                      host=localhost port=8474 version=git-8e40aad
INFO[0002] Accepted client                               client=127.0.0.1:57170 name=redis proxy=127.0.0.1:6380 …
```
=> Add -config option for toxiproxy startup

README.md, cli/cli.go
This adds some badges to the README and addresses a few issues that were mentioned with the docs.
1. Mention `--net=host` for docker port forwarding: https://github.com/Shopify/toxiproxy/issues/151
2. Add a link to the freenode irc channel as a badge: https://github.com/Shopify/toxiproxy/issues/147
3. Fix incorrect cli doc for specifying multiple toxic attributes: https://github.com/Shopify/toxiproxy/issues/139
@sirupsen @jpittis
=> README update

README.md
I noticed we don't use 2.1 for Shopify/shopify, which possibly could've surfaced https://github.com/Shopify/toxiproxy/issues/159 before we cut the release. 🔪 
WDYT about making this part of the official release process @xthexder? 🥇 
cc @karlhungus @archelan since you've run into this.
=> readme: add harness testing with shopify/shopify to release checklist

README.md
Reverts Shopify/toxiproxy#162
I was able to reproduce the https://github.com/Shopify/toxiproxy/issues/159 bug in toxiproxy version 2.0.0 on sha 711c9e48311da6f5f4a9f7e89ee4d00c68011c94.
My understanding of the bug is that it has existed ever since the timeout toxic was introduced. The timeout toxic doesn't read input data and other toxics like latency always write output data. This behaviour fundamentally creates the hang. The latency toxic attempts to write data to the timeout toxic and blocks forever.
@sirupsen
=> Revert "readme: add recommending 2.0.0 until issue is fixed"

link.go, link_test.go, testhelper/testhelper.go, testhelper/testhelper_test.go, toxic_collection.go, toxics/timeout.go, toxics/timeout_test.go, toxics/toxic.go
This is a proposed fix to the API hang bug from issue https://github.com/Shopify/toxiproxy/issues/159.
- [Adds a regression test for the bug mentioned above.](https://github.com/Shopify/toxiproxy/blob/f7154cc4ffa799707070e94f671e3abf1fbcace8/toxics/timeout_test.go#L12)
- Fixes the bug by [changing the `timeout` toxic to drop incoming tcp data](https://github.com/Shopify/toxiproxy/blob/f7154cc4ffa799707070e94f671e3abf1fbcace8/toxics/timeout.go#L22-L31) on the ground.
- The `timeout` toxic implements [`CleanupToxic`](https://github.com/Shopify/toxiproxy/blob/f7154cc4ffa799707070e94f671e3abf1fbcace8/toxics/toxic.go#L29-L32) and [closes it's connection](https://github.com/Shopify/toxiproxy/blob/f7154cc4ffa799707070e94f671e3abf1fbcace8/toxics/timeout.go#L36-L38) on cleanup to avoid stream …
=> Timeout hang bug

toxics/timeout.go, toxics/timeout_test.go
https://github.com/Shopify/toxiproxy/pull/168 introduced a bug where `timeout` toxics would drop the first segment it received but not future segments.
This is because I did not put a for loop around the select statement.
Quite amazingly, this was NOT caught by the regression test because the regression test only sends one segment rather than multiple.
- Updates the regression test to send multiple segments.
- Wraps the `timeout` select statement in a for loop.
Here's a screen shot of me attempting to recreate the bug with this branch. Notice that the client does not hang when deleting the latency toxic, proving that https://github.com/Shopify/toxiproxy/issues/159 was indeed fixed.
@sirupsen
=> timeout toxic drops more than just the first segment

cmd/toxiproxy.go
=> Handle SIGTERM to exit cleanly

api.go, api_test.go
This PR provides a temporary fix to an issue where proxies can be created from the browser.
=> Address an issue where a toxiproxy can be used to bypass the Same-Origin Policy in web browsers

cli/cli.go
this commit only changes the usage doc (shown via `toxyproxy-cli toxic`)
=> usage lines did not match example lines

client/client.go
Hey,
this addresses the fix mentioned in #174: Although the Toxiproxy HTTP API does not support HTTPS, it should not prepend `http://` to the endpoint.
```go
client.NewClient("https://example.com")
// Before: http://https//example.com
// After: https://example.com
```
I would love to write a test for this but `endpoint` is not an exported identifier so i'm not sure how to test this as this is basically the first Go code that i have ever written 🙂 
fixes #174
=> only prepend `http://` to endpoint if no protocol was provided

README.md, api.go
I've written a Haskell Toxiproxy client.
It's well tested. (Complete test suite for every endpoint of the API.) So I believe it's appropriate to add to the list of client libraries.
The Haskell HTTP client library I used requires the "text/plain" content type to be labeled with a charset. I think it's reasonable that we expect our version number to be valid utf-8. I've updated the `Content-Type` field of `Version` to specify a charset.
@sirupsen
=> add support for toxiproxy-haskell

.circleci/config.yml, circle.yml, link_test.go
I added go-junit-report as well to make reading the output a little easier.
Verified with an explicit failing test:
https://circleci.com/gh/Shopify/toxiproxy/tree/circle2_test
Will squash before merging.
@jpittis @sirupsen
=> Update CircleCI config to 2.0

cli/cli.go
=> Fix a typo in the CLI documentation.

toxics/timeout.go
This PR fixes
- the OOM caused by unnecessary creation of timer objects even after the request/response is completed. 
Find pprof attached that shows before and after the fix.
Before:
After:
=> Bail out of the loop when the stub Input stream is done

README.md
This PR adds a [rust client](https://github.com/itarato/toxiproxy_rust) to the readme: [docs](https://docs.rs/toxiproxy_rust/0.1.6/toxiproxy_rust/).
To verify: is the client appropriate to link?
=> Add Rust client link

dev.yml
Small one, I was just getting to know `dev` and I saw the following error popping up:
Removing the line `- openssl` fixed the issue.
=> Fixing dev.yml to allow running 'dev up'

.github/workflows/release.yml, .gitignore, .goreleaser.yml, CHANGELOG.md, dev.yml
Currently the `goreleaser` prints all commits.
It also contains the Merge commits from Github.
Example for v2.1.5 would be:
```
* Move to Go Modules from godeps (#253, @epk)
* Update the example in `client/README.md` (#251, @nothinux)
* Update TOC in `README.md` (4ca1eddddfcd0c50c8f6dfb97089bb68e6310fd9, @dwradcliffe)
* Add an example of `config.json` file to `README.md` (#260, @JesseEstum)
* Add Link to Elixir Client (#287, @Jcambass)
* Add Rust client link (#293, @itarato)
* Renovations: formatting code, update dependicies, make govet/staticcheck pass (#294, @dnwe)
* Remove `openssl` from `dev.yml` to use `dev` tool (#298, @pedro-stanaka)
* Update `go` versions in development (#299, @miry)
* Mention `MacPorts` in `README.md` (#290, @amake)
* Fix some typos in `README.md` and …
```
=> Update release changelog generation

CHANGELOG.md, README.md, cli/cli.go, go.mod, proxy_test.go
In #294 introduced a breaking change in client argument parsing.
It requires to write [flags before arguments](https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flags-before-args).
Update help texts and documentation to have POSIX way to use
flags and arguments.
Example:
Before
```shell
$ toxiproxy-cli create shopify_test_redis_master -l localhost:26379 -u localhost:6379
```
After 
```shell
$ toxiproxy-cli create -l localhost:26379 -u localhost:6379 shopify_test_redis_master
```
=> Flags write before arguments in toxiproxy-cli

.github/workflows/analysis.yml, .golangci.yml, CHANGELOG.md, Makefile, dev.yml
Setup a very basic linting tool [golangci-lint](https://golangci-lint.run/).
Disable all linters as the goal of this changes setup automation.
The code required be formatted and will be enabled one by one.
=> Setup linting

CHANGELOG.md, cli/cli.go
This PR introduces reading from the `TOXIPROXY_URL` variable ~~(or `TOXIPROXY_HOST` + `TOXIPROXY_PORT`)~~ as defaults rather than needing to pass in the `-h somehost.railgun:8474` each time any command is run.
This tries to read the normal fallback url and cannot connect since I don't have toxiproxy running on this url.
```
$ go run cli/cli.go list
Failed to retrieve proxies: Get "http://localhost:8474/proxies": dial tcp 127.0.0.1:8474: connect: connection refused
exit status 1
```
Connects to the correct host without the extra flags, even though it is not `127.0.0.1:8474` since the `TOXIPROXY_URL` is set.
```
$ export TOXIPROXY_URL="http://somehost.railgun:8474"
$ go run cli/cli.go list
Name                    Listen          Upstream                Enabled         Toxics …
```
=> Read `TOXIPROXY_*` environment variables if they exist as default values for the hostname

cli/cli.go, client/README.md, client/client.go, client/toxic_option.go
Make sure the main function is not overhelming,
extract portion of lines to separate methods for better read.
Found that client in `toxic add` supports both: `--upstream` and
`--downstream`. Because it tries to create 2 toxic with single name it
produces the error when tries add `--downstream` toxic, and in same time
creates the `--upstream` toxic.
Update the usage help to  mention about argument `--toxicity <float>`
To remove confusion update the client usage help to support only one in
same time. Return error message in case 2 flags provided.
Introduce a new way to add toxics with client: 
Provide a structure`ToxicOptions` with all required options and pass to `client.AddToxic` to add toxic.
=> Extract client flags specs to seperate methods

CHANGELOG.md, Makefile, bin/release_test
There is a make task to check binaries correctnes that is always success.
It seems the task release-test always was success, because the variables were not
used in the strings.
Extract code from Makefile to make it easy to run single tests
and in same time to keep using only bash.
Also add posibility to run task on arm machines.
=> fix: The release-test task is always success

CHANGELOG.md, Dockerfile, README.md, api.go, bin/e2e, cmd/cli/cli.go, cmd/server/server.go
Add possobility to change output verbosity via environment varaible
`LOG_LEVEL`. There are several values: panic, fatal, error, warn or
warning, info, debug and trace.
By default `info` is used.
close: #343
=> Allow to change log level for server.

CHANGELOG.md, Makefile
> On macOS 12 a new malloc implementation (nano) is used by default, and apparently it reserves address range 0x600000000000-0x600020000000, which conflicts with the address range that TSAN uses for Go
> https://github.com/golang/go/issues/49138
The fix is already merged in upstream, but yet not released. Change will perform OS and Golang version check and add `MallocNanoZone=0` on MacOS with go17 <= 1.17.5 (I hope that 1.17.6 will include upstream fix)
**Question:** Do we want to include other Go versions? Or we consider 1.17 as the main one on MacOS?
=> Add fix for tests on MacOS 12 with -race flag for go17

bin/e2e, bin/release_test, cmd/server/server.go
Add flag `-version` to print the current version and exit.
```shell
$ toxiproxy-server -version
toxiproxy-server version v2.3.0
```
closes: #348
=> Print the server version with command line

.editorconfig, .github/dependabot.yml, .github/probots.yml, .github/workflows/analysis.yml, .github/workflows/release.yml, .github/workflows/test.yml, .golangci.yml, .goreleaser.yml, .yamllint.yml, CHANGELOG.md, Makefile, dev.yml, scripts/test-release
Add yamllint and update the yml files accordingly.
=> Introduce yaml linter

README.md, RELEASE.md, metrics_test.go
=> Update release documentation

.editorconfig, .github/workflows/test.yml, .golangci.yml, CHANGELOG.md, dev.yml, go.mod, go.sum, metrics_test.go
Add 1.18 to the list of CI as supported version.
Update test to check metrics with tags.
=> Use go 1.18

.github/dependabot.yml, .github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md, dev.yml, go.mod
Update go version and github actions to tests against 1.19.
Drop support of 1.14.
=> Support go 1.19

CHANGELOG.md, api.go, metrics_test.go, proxy.go, proxy_collection.go, toxics/toxic_test.go, toxiproxy_test.go
NewProxy always uses 4 lines to initialize name, listen and upstream addresses.
Combine them in single initialization via arguments.
=> Update toxiproxy.NewProxy signature to support common attributes

CHANGELOG.md, api.go
Introduce TimeoutHandler to return with 503 http status code,
if request processing is more than 5 seconds.
=> Add Timeouthandler for HTTP API server.

CHANGELOG.md, api.go
Move stopBrowserMiddleware after logging middleware,
but before timeoutMiddleware.
Set Write and Read timeouts for http server.
=> Setup http server timeout connections

.github/workflows/analysis.yml, .golangci.yml, CHANGELOG.md, link.go, test/e2e/endpoint.go, toxics/limit_data_test.go, toxics/slicer.go
Linter shows warning messages to update config:
```shell
$ golangci-lint run
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
```
Remove those plugins.
Resolve new golangci-linter checks:
- One of the big change: Setup timeouts for HTTP servers.
UPDATE: Do not merge. Need to test issue base on previous versions.
=> Upgrade golangci linter

.github/workflows/test.yml
Currently `Test / build` step in test workflow finishes 9 minutes.
Update workflow to run build pahse only for Linux.
=> Limit test phase of build only for linux

toxic_collection.go
Use slice of array to skip first element in function `findToxicByName`.
=> Update findToxicByName to remove check index 0

api.go, link.go, link_test.go, toxic_collection.go, toxics/latency_test.go, toxics/timeout_test.go, toxics/toxic_test.go
Propogate context with logger to ToxicCollection, ToxicLink.
=> Improve with logging deep components

cmd/server/server.go, scripts/test-e2e, toxics/bandwidth.go
Add more log events for Trace level to debug bandwidth toxic issues.
Run server
```shell
$ LOG_LEVEL=trace ./dist/toxiproxy-server
```
Create proxy and toxics:
```shell
$ ./dist/toxiproxy-cli create -l ":2001" -u "example.com:80" shopify_http
Created new proxy shopify_http
$ ./dist/toxiproxy-cli toxic add --downstream --type=bandwidth --toxicName="bandwidth_downstream1" shopify_http
Added downstream bandwidth toxic 'bandwidth_downstream1' on proxy 'shopify_http'
$ ./dist/toxiproxy-cli toxic add --upstream --type=bandwidth --toxicName="bandwidth_upstream1" shopify_http
Added upstream bandwidth toxic 'bandwidth_upstream1' on proxy 'shopify_http'
```
Create a connection:
```shell
$ nc localhost 2001
GET /
```
During this time remove a toxic:
```shell
$ ./dist/toxiproxy-cli toxic delete …
```
=> Add trace logger events for Bandwidth toxic

CHANGELOG.md, Makefile, api.go, link.go, link_test.go, scripts/hazelcast.xml, scripts/test-e2e, scripts/test-e2e-hazelcast, toxics/bandwidth.go, toxics/toxic.go, toxics/toxic_test.go
It could happen when Link has no reciever and there is some packets in buffer.
It produces deadlock.
=> ToxicStub allow to unblocking write to Output

CHANGELOG.md, api.go, api_test.go, cmd/server/server.go, scripts/test-e2e-hazelcast
Make sure toxiproxy HTTP server close gracefully connection.
Extract endpoints initialization in separate method Routes.
Update notify signal to handle SIGTERM and SIGINT.
=> Add gracefull shutdown to HTTP server.

CHANGELOG.md, api.go, api_test.go, client/api_error.go, client/client.go, client/client_test.go, client/proxy.go, cmd/cli/cli.go
Introduce single Client httpClient for all cli requests.
It allows to add request headers in single place.
For example adds `User-Agent` HTTP header for all requests as `"toxiproxy-cli/<version> <os>/<runtime>"`.
Parse response on success or errors.
Set content type as json always.
=> Use single http client for cli

CHANGELOG.md, api.go, api_test.go, cmd/server/server.go
Provide addr instead of host and port as separate parameters.
Old:
```go
server.Listen("localhost", "8474")
```
New:
```go
server.Listen("localhost:8474")
```
=> Update interface of ApiServer.Listen to use addr.

CREATING_TOXICS.md, README.md, _examples/tests/README.md, _examples/tests/cluster.yml, _examples/tests/db.go, _examples/tests/db_test.go, _examples/tests/main.go, _examples/tests/models.go, _examples/tests/resources.yml, _examples/toxics/README.md, _examples/toxics/debug_toxic.go, _examples/toxics/http_toxic.go, scripts/test-e2e-hazelcast
To easy onboard people to use toxiproxy examples are helpful. 
Provide example how to add new Toxic.
Setup example folder with setup application and tests with Toxiproxy.
=> Example of usage Toxiproxy in tests

.github/workflows/analysis.yml, .github/workflows/test.yml, README.md, RELEASE.md
Merging the master changes to main to replace branch name to make it more inclusive.
This change involves replacing the usages of master to main from readme, release.md and GH actions
Builds are failing due to version mismatch between golangci-lint-action and golangci-lint. So the `golangci-lint` version is also updated
=> Updating golangci-lint version and default trunk name changes

.github/workflows/analysis.yml, .github/workflows/test.yml, README.md, RELEASE.md
These changes should be only on `main` branch and not on `master` branch which got merged accidentally.
On this repo, the default branch is now `main` and the GH actions are updated on `main`
This PR will leave `master` branch untouched w.r.t trunk name changes.
Once changes are verified, the `master` branch will be cleaned off.
=> Revert trunk name changes on GH actions and readmes for master

.github/workflows/analysis.yml, .github/workflows/test.yml, README.md, RELEASE.md
For consistency with other projects, renaming the trunk branch from `master` to `main`. Once the documentation is updated I will make this change for the GH repo as well.
=> Rename trunk branch to `main`

go.mod
Specifying the patch version in the Go module means that any other modules using this need to comply. This has caused our `go.mod` file to change. While is not necessarily bad, we only use this library for testing so it feels wrong to have to pin our own version to match this module.
By only specifying the major+minor version in the `go.mod` file, we let the Go toolchain pick the appropriate version that is available when building the binary but requiring at least the `1.22` version.
=> Do not pin minimum patch version in module

README.md
The code for the timeout toxic when timeout is set to zero simply reads from the input and then if it gets some data just has a comment: "// Drop the data on the ground".  This change updates the docs do indicate the data is dropped, not delayed, until the texic is removed.
=> Update README.md - clarify timeout toxic behavior

.github/workflows/analysis.yml, link_test.go
The linter CI job is failing per the error in this job: https://github.com/Shopify/toxiproxy/actions/runs/11640869223/job/32418715356
It fails on the linter, however there is no logs around why it fails. I've fixed the linter errors on main (there were 2) as well as incremented the version of the linter to 1.62.2 and that seems to have resolved the issue.
How to 🎩 :
1. Do a `golangci-lint run` and verify it succeeds (no errors should print).
=> Fixes some linter errors to fix workflow error

client/README.md
Updates the full example in the client readme to compile. It was broken and didn't reflect the current API. I also removed an unnecessary example test that wasn't necessary to get a feel for how to use Toxiproxy.
=> Update client readme example to compile with previous API changes
