Shopify/toxiproxy

api_test.go, client/client.go
Changes to a more nice Go API where we can do things like:
```go
proxy.Create()
proxy.Enabled = false
proxy.Save()
proxy.Destroy()
client.Proxies()
```
Instead of doing everything on the client.
Follow up PRs will clean up errors, split into files, add toxic API.
@xthexder
=> client: change to more idiomatic api

README.md
https://github.com/Shopify/toxiproxy-ruby/pull/8
@byroot @xthexder
=> readme: update for new populate api

client/client.go
=> Set the client on proxies returned correctly

toxic_collection.go, toxic_test.go
@eapache @Sirupsen 
Should fix https://github.com/Shopify/toxiproxy/issues/41 you'll need to confirm that @eapache
=> Fix toxic disabling logic and add persistent connection tests

README.md
Hello :)
I have a terrible habit of correcting code as I read it. I decided to send you the results.
<3
=> Miscellaneous README fixes

README.md, api_test.go, client/README.md, client/client.go
=> client: add toxics and promote from wip

README.md
Further to @Sirupsen tweet I have added a link to my .net client for Toxiproxy.
=> Added a link to a toxiproxy .net client.

CHANGELOG.md, README.md, toxic_bandwidth.go, toxic_collection.go, toxic_test.go
@Sirupsen @pushrax 
Depends on https://github.com/Shopify/toxiproxy/pull/47
Adds a bandwidth toxic for limiting connections to a certain bitrate.
=> Add Bandwidth toxic

README.md
[Mostly complete and tested.](https://github.com/ihsw/toxiproxy-php-client)
In the near future I will be starting a [Symfony](http://symfony.com/) bundle as well.
=> PHP client

CHANGELOG.md, api_test.go, client/client.go
This makes using the client with toxics a lot more enjoyable!
@xthexder
=> client/go: proper types for toxics and collections

CHANGELOG.md, Dockerfile, Makefile, README.md
This'll make it even easier to include it for development and CI in other projects that already use Docker and is extremely simple to do with Go.
@xthexder
=> docker: initial commit of dockerfile

Makefile, README.md
=> docker: move to shopify org

README.md
I wrote a node client.
You can find it here: http://github.com/DLion/toxiproxy-node
=> Node Client

CHANGELOG.md, api.go, api_test.go, proxy_collection.go, proxy_collection_test.go
Fixes https://github.com/Shopify/toxiproxy/issues/68
@Sirupsen
=> Fix proxy name conflict leaking a port

api.go, api_test.go, client/client.go, link.go, link_test.go, proxy.go, stream/io_chan.go, toxic_collection.go, toxics/bandwidth_test.go, toxics/latency_test.go, toxics/toxic.go, toxics/toxic_test.go
@Sirupsen @eapache 
As suggested in PR https://github.com/Shopify/toxiproxy/pull/62
=> Remove stream direction from api urls

CREATING_TOXICS.md, README.md
=> Update README for 2.0

README.md
I noticed this when I was trying to use the example code provided.
=> Fixed hash usage in example

api.go, api_test.go
Per discussion in https://github.com/Shopify/toxiproxy/pull/83 
@xthexder
=> api: improve stream error message

README.md, api.go, client/client.go
As per discussion in https://github.com/Shopify/toxiproxy/pull/83
@xthexder
=> api: change reset method to be POST

README.md
Update docs to point to latest release. See #106
@Sirupsen
=> update readme to link 2.0.0 releases

README.md, toxics/limit_data.go, toxics/limit_data_test.go
As mentioned in #122 here is PR ... sort of first experience with golang.
=> Add toxic limiting size of transmitted data

README.md
=> readme: add recommending 2.0.0 until issue is fixed

CHANGELOG.md
=> add Handle SIGTERM to exit cleanly to changelog

README.md
=> Add example config.json file to README.md

.github/workflows/analysis.yml
Setup Github actions for code security analysis.
Verify the source code on vulnerabilities.
=> Setup Github actions for code security analysis

.golangci.yml, CHANGELOG.md, Makefile, api.go, api_test.go, cli/cli.go, client/client.go, link.go, link_test.go, proxy_test.go, toxic_collection.go, toxics/bandwidth_test.go, toxics/latency_test.go, toxics/timeout.go, toxics/timeout_test.go, toxics/toxic.go, toxics/toxic_test.go
Add linter to check the max line length.
Use https://github.com/segmentio/golines to format most of files.
=> Set max line 100 characters

.github/workflows/test.yml, Makefile
Add a check to Github actions to run bench tests.
Update Makefile to run benchmark tests.
=> Run benchmark tests in CI/CD

stream/io_chan_test.go, testhelper/upstream.go, toxics/bandwidth_test.go, toxics/latency_test.go
Extract common part in test to initialize the test upstream server.
=> Extract initialization of upstream server in tests

Makefile, proxy.go
Decrease the size of the proxy.server method.
=> Split proxy methods to small one

.golangci.yml, CHANGELOG.md, api_test.go, cli/cli.go, client/client.go, cmd/toxiproxy.go, link.go, link_test.go, proxy.go, stream/io_chan.go, testing/benchmark_test.go, toxic_collection.go, toxics/bandwidth.go, toxics/limit_data.go, toxics/toxic.go
Base on some examples picked few more linters.
=> Support a list of well knonwn linters

.editorconfig, .github/workflows/analysis.yml, Makefile, scripts/test-e2e, scripts/test-release
Use https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd and https://github.com/koalaman/shellcheck
=> Introduce shell linter
